baseURL = "https://www.cgs.iitk.ac.in/user/nsrivast/platipus-lab/"
languageCode = "en-us"
title = "PLATIPUS Lab"
theme = "notrack"
newContentEditor = "nvim"
mainSections = []
# disqusShortname = "example"
paginate = 4

[params]
  author = ""
  siteHeading = "PLATIPUS Lab" # defaults to author
  favicon = "" # Adds a small icon next to the page title in a tab
  showBlogLatest = false
  mainSections = []
  showTaxonomyLinks = false

  [params.social]
    github = "example"
    linkedin = "example"
    email = "example@example.com"
    mastodon = "example"
    rss = "rss won't use the value you give it so you can put anything here"
    keybase = "example"
